jaksafe/report/urls.py
from django.conf.urls import patterns, url
from report import views

urlpatterns = patterns('',
    url(r'^auto/$', views.report_auto, name='report_auto'),
    url(r'^adhoc/$', views.report_adhoc, name='report_adhoc'),
    url(r'^flood/$', views.report_flood, name='report_flood'),
    url(r'^impact_config/$', views.report_impact_config, name='report_impact_config'),
    url(r'^assumptions_config/$', views.report_assumptions_config, name='report_assumptions_config'),
    url(r'^aggregate_config/$', views.report_aggregate_config, name='report_aggregate_config'),
    url(r'^boundary_config/$', views.report_boundary_config, name='report_boundary_config'),
    url(r'^exposure_config/$', views.report_exposure_config, name='report_exposure_config'),
    url(r'^global_config/$', views.report_global_config, name='report_global_config'),
    url(r'^login/$', views.report_login, name='report_login'),
    url(r'^logout/$', views.report_logout, name='report_logout'),
)

jaksafe/report/models.py
from django.db import models

# Create your models here.

jaksafe/report/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import filesizeformat
from django.conf import settings

class ImpactClassForm(forms.Form):
    impact_class_file = forms.FileField(
        label="",
        help_text="Must be a .csv file.",
    )
    
    def clean_impact_class_file(self):
        the_file = self.cleaned_data['impact_class_file']
        content_type = the_file.content_type.split('/')[1]
        size = the_file._size
        filename = the_file.name
        
        print 'DEBUG filename = %s' % filename
        print 'DEBUG content_type = %s' % content_type
        
        if filename.lower().endswith('.csv') or content_type in settings.CONTENT_TYPES:
            if size > settings.MAX_UPLOAD_SIZE:
                raise forms.ValidationError(_("File size is over %s. Current file size %s.") % (filesizeformat(settings.MAX_UPLOAD_SIZE), filesizeformat(size)))
        else:
            raise forms.ValidationError(_('File type is not supported.'))
        
        return the_file

class AggregateForm(forms.Form):
    aggregate_file = forms.FileField(
        label="",
        help_text="Must be a .csv file.",
    )
    
    def clean_aggregate_file(self):
        the_file = self.cleaned_data['aggregate_file']
        content_type = the_file.content_type.split('/')[1]
        size = the_file._size
        filename = the_file.name
        
        print 'DEBUG filename = %s' % filename
        print 'DEBUG content_type = %s' % content_type
        
        if filename.lower().endswith('.csv') or content_type in settings.CONTENT_TYPES:
            if size > settings.MAX_UPLOAD_SIZE:
                raise forms.ValidationError(_("File size is over %s. Current file size %s.") % (filesizeformat(settings.MAX_UPLOAD_SIZE), filesizeformat(size)))
        else:
            raise forms.ValidationError(_('File type is not supported.'))
        
        return the_file

class AssumptionsDamageForm(forms.Form):
    assumptions_damage_file = forms.FileField(
        label="",
        help_text="Must be a .csv file.",
    )
    
    def clean_assumptions_damage_file(self):
        the_file = self.cleaned_data['assumptions_damage_file']
        content_type = the_file.content_type.split('/')[1]
        size = the_file._size
        filename = the_file.name
        
        print 'DEBUG filename = %s' % filename
        print 'DEBUG content_type = %s' % content_type
        
        if filename.lower().endswith('.csv') or content_type in settings.CONTENT_TYPES:
            if size > settings.MAX_UPLOAD_SIZE:
                raise forms.ValidationError(_("File size is over %s. Current file size %s.") % (filesizeformat(settings.MAX_UPLOAD_SIZE), filesizeformat(size)))
        else:
            raise forms.ValidationError(_('File type is not supported.'))
        
        return the_file

class AssumptionsLossForm(forms.Form):
    assumptions_loss_file = forms.FileField(
        label="",
        help_text="Must be a .csv file.",
    )
    
    def clean_assumptions_loss_file(self):
        the_file = self.cleaned_data['assumptions_loss_file']
        content_type = the_file.content_type.split('/')[1]
        size = the_file._size
        filename = the_file.name
        
        print 'DEBUG filename = %s' % filename
        print 'DEBUG content_type = %s' % content_type
        
        if filename.lower().endswith('.csv') or content_type in settings.CONTENT_TYPES:
            if size > settings.MAX_UPLOAD_SIZE:
                raise forms.ValidationError(_("File size is over %s. Current file size %s.") % (filesizeformat(settings.MAX_UPLOAD_SIZE), filesizeformat(size)))
        else:
            raise forms.ValidationError(_('File type is not supported.'))
        
        return the_file

class AssumptionsAggregateForm(forms.Form):
    assumptions_aggregate_file = forms.FileField(
        label="",
        help_text="Must be a .csv file.",
    )
    
    def clean_assumptions_aggregate_file(self):
        the_file = self.cleaned_data['assumptions_aggregate_file']
        content_type = the_file.content_type.split('/')[1]
        size = the_file._size
        filename = the_file.name
        
        print 'DEBUG filename = %s' % filename
        print 'DEBUG content_type = %s' % content_type
        
        if filename.lower().endswith('.csv') or content_type in settings.CONTENT_TYPES:
            if size > settings.MAX_UPLOAD_SIZE:
                raise forms.ValidationError(_("File size is over %s. Current file size %s.") % (filesizeformat(settings.MAX_UPLOAD_SIZE), filesizeformat(size)))
        else:
            raise forms.ValidationError(_('File type is not supported.'))
        
        return the_file

class AssumptionsInsuranceForm(forms.Form):
    assumptions_insurance_file = forms.FileField(
        label="",
        help_text="Must be a .csv file.",
    )
    
    def clean_assumptions_insurance_file(self):
        the_file = self.cleaned_data['assumptions_insurance_file']
        content_type = the_file.content_type.split('/')[1]
        size = the_file._size
        filename = the_file.name
        
        print 'DEBUG filename = %s' % filename
        print 'DEBUG content_type = %s' % content_type
        
        if filename.lower().endswith('.csv') or content_type in settings.CONTENT_TYPES:
            if size > settings.MAX_UPLOAD_SIZE:
                raise forms.ValidationError(_("File size is over %s. Current file size %s.") % (filesizeformat(settings.MAX_UPLOAD_SIZE), filesizeformat(size)))
        else:
            raise forms.ValidationError(_('File type is not supported.'))
        
        return the_file

class AssumptionsInsurancePenetrationForm(forms.Form):
    assumptions_insurance_penetration_file = forms.FileField(
        label="",
        help_text="Must be a .csv file.",
    )
    
    def clean_assumptions_insurance_penetration_file(self):
        the_file = self.cleaned_data['assumptions_insurance_penetration_file']
        content_type = the_file.content_type.split('/')[1]
        size = the_file._size
        filename = the_file.name
        
        print 'DEBUG filename = %s' % filename
        print 'DEBUG content_type = %s' % content_type
        
        if filename.lower().endswith('.csv') or content_type in settings.CONTENT_TYPES:
            if size > settings.MAX_UPLOAD_SIZE:
                raise forms.ValidationError(_("File size is over %s. Current file size %s.") % (filesizeformat(settings.MAX_UPLOAD_SIZE), filesizeformat(size)))
        else:
            raise forms.ValidationError(_('File type is not supported.'))
        
        return the_file

class BoundaryForm(forms.Form):
    boundary_shp_file = forms.FileField(
        label="",
        help_text="Must be a .shp file",
    )
    
    boundary_shx_file = forms.FileField(
        label="",
        help_text="Must be a .shx file",
    )
    
    boundary_dbf_file = forms.FileField(
        label="",
        help_text="Must be a .dbf file",
    )
    
    boundary_prj_file = forms.FileField(
        label="",
        help_text="Must be a .prj file",
    )
    
    boundary_qpj_file = forms.FileField(
        label="",
        help_text="Must be a .qpj file",
    )
    
    def clean(self):
        boundary_shp_file = self.cleaned_data.get('boundary_shp_file')
        boundary_shx_file = self.cleaned_data.get('boundary_shx_file')
        boundary_dbf_file = self.cleaned_data.get('boundary_dbf_file')
        boundary_prj_file = self.cleaned_data.get('boundary_prj_file')
        boundary_qpj_file = self.cleaned_data.get('boundary_qpj_file')
        
        if (boundary_shp_file == False or boundary_shx_file == False or boundary_dbf_file == False or boundary_prj_file == False or boundary_qpj_file == False):
            raise forms.ValidationError(_('Upload file not found.'))
        
        if boundary_shp_file:
            filename = boundary_shp_file.name
            content_type = boundary_shp_file.content_type.split('/')[1]
            size = boundary_shp_file._size
            
            if (filename.lower().endswith('.shp') == False):
                print 'DEBUG invalid file type'
                raise forms.ValidationError(_('Invalid file type.'))
            
            print 'DEBUG %s %s %s' % (filename, content_type, size)
        
        if boundary_shx_file:
            filename = boundary_shx_file.name
            content_type = boundary_shx_file.content_type.split('/')[1]
            size = boundary_shx_file._size
            
            if (filename.lower().endswith('.shx') == False):
                print 'DEBUG invalid file type'
                raise forms.ValidationError(_('Invalid file type.'))
            
            print 'DEBUG %s %s %s' % (filename, content_type, size)
        
        if boundary_dbf_file:
            filename = boundary_dbf_file.name
            content_type = boundary_dbf_file.content_type.split('/')[1]
            size = boundary_dbf_file._size
            
            if (filename.lower().endswith('.dbf') == False):
                print 'DEBUG invalid file type'
                raise forms.ValidationError(_('Invalid file type.'))
            
            print 'DEBUG %s %s %s' % (filename, content_type, size)
        
        if boundary_prj_file:
            filename = boundary_prj_file.name
            content_type = boundary_prj_file.content_type.split('/')[1]
            size = boundary_prj_file._size
            
            if (filename.lower().endswith('.prj') == False):
                print 'DEBUG invalid file type'
                raise forms.ValidationError(_('Invalid file type.'))
            
            print 'DEBUG %s %s %s' % (filename, content_type, size)
        
        if boundary_qpj_file:
            filename = boundary_qpj_file.name
            content_type = boundary_qpj_file.content_type.split('/')[1]
            size = boundary_qpj_file._size
            

jaksafe/report/templates/report/report_aggregate_config.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ page_title }}{{ block.super }}{% endblock %}

{% block extra_header %}
{% endblock %}

{% block content %}
{% if errors %}
<div class="alert alert-danger" role="alert">
    <a href="javascript:void(0);" class="close" data-dismiss="alert">&times;</a>
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Error:</span>
    {% for error in errors %}
        {% trans error %}
    {% endfor %}
</div>
{% endif %}

{% if successes %}
<div class="alert alert-success" role="alert">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
    <span class="sr-only">Success:</span>
    {% for success in successes %}
        {% trans success %}
    {% endfor %}
</div>
{% endif %}

{% if messages %}
    {% for message in messages %}
    {% if message.tags == 'success' %}
    <div class="alert alert-success" role="alert">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
        <span class="sr-only">Success:</span>
        {{ message }}
    </div>
    {% elif message.tags == 'error' %}
    <div class="alert alert-danger" role="alert">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        {{ message }}
    </div>
    {% endif %}
    {% endfor %}
{% endif %}

<div id="heading" id="" class="row mb-20">
    <div class="col-md-12">
        <h3>{{ page_title }}</h3>
    </div>
</div>

<div id="filter" class="row mb-20">
    <div class="col-md-12">
        <p><strong>{% trans "Upload Aggregate Config File" %}</strong></p>
        <p>{{ form.aggregate_file.label_tag }} {{ form.aggregate_file.help_text }}</p>
        <form method="post" enctype="multipart/form-data" action="{% url "report_aggregate_config" %}">
            <div class="form-group">
                
                {{ form.non_field_errors }}
                {{ form.aggregate_file.errors }}
                
                <input id="id_aggregate_file" name="aggregate_file" type="file">
            </div>
            <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
            <button type="submit" class="btn btn-default">{% trans "Upload" %}</button>
            {% if aggregate_download_url %} <a class="btn btn-default" href="{{ aggregate_download_url }}" target="_blank">{% trans "Download This Config" %}</a>{% endif %}
        </form>
    </div>
</div>

<div id="content" class="row mb-20">
    <div class="col-md-12">
        {% if csvlist %}
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>{% trans "Provinsi" %}</th>
                    <th>{% trans "Kota" %}</th>
                    <th>{% trans "Kecamatan" %}</th>
                    <th>{% trans "Kelurahan" %}</th>
                    <th>{% trans "RW" %}</th>
                    <th>{% trans "RT" %}</th>
                    <th>{% trans "Subsektor" %}</th>
                    <th>{% trans "Aset" %}</th>
                    <th>{% trans "Jumlah" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for row in csvlist %}
                <tr>
                    <td>{{ forloop.counter }}.</td>
                    <td>{{ row.PROVINSI }}</td>
                    <td>{{ row.KOTA }}</td>
                    <td>{{ row.KECAMATAN }}</td>
                    <td>{{ row.KELURAHAN }}</td>
                    <td>{{ row.RW }}</td>
                    <td>{{ row.RT }}</td>
                    <td>{{ row.SUBSEKTOR }}</td>
                    <td>{{ row.ASET }}</td>
                    <td>{{ row.JUMLAH }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p class="text-center">{% trans "Error: no config file found." %}</p>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block extra_footer %}
{% endblock %}

jaksafe/report/templates/report/report_boundary_config.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ page_title }}{{ block.super }}{% endblock %}

{% block extra_header %}
{% endblock %}

{% block content %}
{% if errors %}
<div class="alert alert-danger" role="alert">
    <a href="javascript:void(0);" class="close" data-dismiss="alert">&times;</a>
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Error:</span>
    {% for error in errors %}
        {% trans error %}
    {% endfor %}
</div>
{% endif %}

{% if successes %}
<div class="alert alert-success" role="alert">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
    <span class="sr-only">Success:</span>
    {% for success in successes %}
        {% trans success %}
    {% endfor %}
</div>
{% endif %}

{% if messages %}
    {% for message in messages %}
    {% if message.tags == 'success' %}
    <div class="alert alert-success" role="alert">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
        <span class="sr-only">Success:</span>
        {{ message }}
    </div>
    {% elif message.tags == 'error' %}
    <div class="alert alert-danger" role="alert">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        {{ message }}
    </div>
    {% endif %}
    {% endfor %}
{% endif %}

<div id="heading" id="" class="row mb-20">
    <div class="col-md-12">
        <h3>{{ page_title }}</h3>
    </div>
</div>

<form method="post" enctype="multipart/form-data" action="{% url "report_boundary_config" %}">

<div class="row mb-20">
    <div class="col-md-6">
        <p><strong>{% trans "Upload Boundary SHP File" %}</strong>{% if shp_download_url %} <a class="btn btn-default" href="{{ shp_download_url }}" target="_blank">{% trans "Download File" %}</a>{% endif %}</p>
        <p>{{ form.boundary_shp_file.label_tag }} {{ form.boundary_shp_file.help_text }}</p>
        <div class="form-group">
            
            {{ form.non_field_errors }}
            {{ form.boundary_shp_file.errors }}
            
            <input id="id_boundary_shp_file" name="boundary_shp_file" type="file">
        </div>
        
        <p><strong>{% trans "Upload Boundary SHX File" %}</strong>{% if shx_download_url %} <a class="btn btn-default" href="{{ shx_download_url }}" target="_blank">{% trans "Download File" %}</a>{% endif %}</p>
        <p>{{ form.boundary_shx_file.label_tag }} {{ form.boundary_shx_file.help_text }}</p>
        <div class="form-group">
            
            {{ form.non_field_errors }}
            {{ form.boundary_shx_file.errors }}
            
            <input id="id_boundary_shx_file" name="boundary_shx_file" type="file">
        </div>
        
        <p><strong>{% trans "Upload Boundary DBF File" %}</strong>{% if dbf_download_url %} <a class="btn btn-default" href="{{ dbf_download_url }}" target="_blank">{% trans "Download File" %}</a>{% endif %}</p>
        <p>{{ form.boundary_dbf_file.label_tag }} {{ form.boundary_dbf_file.help_text }}</p>
        <div class="form-group">
            
            {{ form.non_field_errors }}
            {{ form.boundary_dbf_file.errors }}
            
            <input id="id_boundary_dbf_file" name="boundary_dbf_file" type="file">
        </div>
        
        <p><strong>{% trans "Upload Boundary PRJ File" %}</strong>{% if prj_download_url %} <a class="btn btn-default" href="{{ prj_download_url }}" target="_blank">{% trans "Download File" %}</a>{% endif %}</p>
        <p>{{ form.boundary_prj_file.label_tag }} {{ form.boundary_prj_file.help_text }}</p>
        <div class="form-group">
            
            {{ form.non_field_errors }}
            {{ form.boundary_prj_file.errors }}
            
            <input id="id_boundary_prj_file" name="boundary_prj_file" type="file">
        </div>
        
        <p><strong>{% trans "Upload Boundary QPJ File" %}</strong>{% if qpj_download_url %} <a class="btn btn-default" href="{{ qpj_download_url }}" target="_blank">{% trans "Download File" %}</a>{% endif %}</p>
        <p>{{ form.boundary_qpj_file.label_tag }} {{ form.boundary_qpj_file.help_text }}</p>
        <div class="form-group">
            
            {{ form.non_field_errors }}
            {{ form.boundary_qpj_file.errors }}
            
            <input id="id_boundary_qpj_file" name="boundary_qpj_file" type="file">
        </div>
        
        <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
        <button type="submit" class="btn btn-default pull-right">{% trans "Upload All" %}</button>
    </div>
</div>
</form>
{% endblock %}

{% block extra_footer %}
{% endblock %}

jaksafe/report/templates/report/report_global_config.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ page_title }}{{ block.super }}{% endblock %}

{% block extra_header %}
{% endblock %}

{% block content %}
{% if errors %}
<div class="alert alert-danger" role="alert">
    <a href="javascript:void(0);" class="close" data-dismiss="alert">&times;</a>
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Error:</span>
    {% for error in errors %}
        {% trans error %}
    {% endfor %}
</div>
{% endif %}

{% if successes %}
<div class="alert alert-success" role="alert">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
    <span class="sr-only">Success:</span>
    {% for success in successes %}
        {% trans success %}
    {% endfor %}
</div>
{% endif %}

{% if messages %}
    {% for message in messages %}
    {% if message.tags == 'success' %}
    <div class="alert alert-success" role="alert">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
        <span class="sr-only">Success:</span>
        {{ message }}
    </div>
    {% elif message.tags == 'error' %}
    <div class="alert alert-danger" role="alert">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        {{ message }}
    </div>
    {% endif %}
    {% endfor %}
{% endif %}

<div id="heading" id="" class="row mb-20">
    <div class="col-md-12">
        <h3>{{ page_title }}</h3>
    </div>
</div>

<div id="filter" class="row mb-20">
    <div class="col-md-12">
        <p><strong>{% trans "Upload Global Config File" %}</strong></p>
        <p>{{ form.global_config_file.label_tag }} {{ form.global_config_file.help_text }}</p>
        <form method="post" enctype="multipart/form-data" action="{% url "report_global_config" %}">
            <div class="form-group">
                
                {{ form.non_field_errors }}
                {{ form.global_config_file.errors }}
                
                <input id="id_global_config_file" name="global_config_file" type="file">
            </div>
            <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
            <button type="submit" class="btn btn-default">{% trans "Upload" %}</button>
        </form>
    </div>
</div>

<div id="content" class="row mb-20">
    <div class="col-md-12">
        {% if global_config %}
        <p><strong>{% trans "Current Global Config File" %}</strong></p>
        <textarea class="form-control" rows="10" readonly>{{ global_config }}</textarea>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block extra_footer %}
{% endblock %}

jaksafe/report/templates/report/report_impact_config.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ page_title }}{{ block.super }}{% endblock %}

{% block extra_header %}
{% endblock %}

{% block content %}
{% if errors %}
<div class="alert alert-danger" role="alert">
    <a href="javascript:void(0);" class="close" data-dismiss="alert">&times;</a>
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Error:</span>
    {% for error in errors %}
        {% trans error %}
    {% endfor %}
</div>
{% endif %}

{% if successes %}
<div class="alert alert-success" role="alert">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
    <span class="sr-only">Success:</span>
    {% for success in successes %}
        {% trans success %}
    {% endfor %}
</div>
{% endif %}

{% if messages %}
    {% for message in messages %}
    {% if message.tags == 'success' %}
    <div class="alert alert-success" role="alert">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
        <span class="sr-only">Success:</span>
        {{ message }}
    </div>
    {% elif message.tags == 'error' %}
    <div class="alert alert-danger" role="alert">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        {{ message }}
    </div>
    {% endif %}
    {% endfor %}
{% endif %}

<div id="heading" id="" class="row mb-20">
    <div class="col-md-12">
        <h3>{{ page_title }}</h3>
    </div>
</div>

<div id="filter" class="row mb-20">
    <div class="col-md-12">
        <p><strong>{% trans "Upload Impact Class Config File" %}</strong></p>
        <p>{{ form.impact_class_file.label_tag }} {{ form.impact_class_file.help_text }}</p>
        <form method="post" enctype="multipart/form-data" action="{% url "report_impact_config" %}">
            <div class="form-group">
                
                {{ form.non_field_errors }}
                {{ form.impact_class_file.errors }}
                
                <input id="id_impact_class_file" name="impact_class_file" type="file">
            </div>
            <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
            <button type="submit" class="btn btn-default">{% trans "Upload" %}</button>
            {% if impact_class_download_url %} <a class="btn btn-default" href="{{ impact_class_download_url }}" target="_blank">{% trans "Download This Config" %}</a>{% endif %}
        </form>
    </div>
</div>

<div id="content" class="row mb-20">
    <div class="col-md-12">
        {% if csvlist %}
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>{% trans "Kelas" %}</th>
                    <th>{% trans "Tinggi Min" %}</th>
                    <th>{% trans "Tinggi Max" %}</th>
                    <th>{% trans "Durasi Min" %}</th>
                    <th>{% trans "Durasi Max" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for row in csvlist %}
                <tr>
                    <td>{{ forloop.counter }}.</td>
                    <td>{{ row.kelas }}</td>
                    <td>
                    {% if row.kedalaman_bawah == 'NULL' %}
                    {% trans "Terdampak" %}
                    {% else %}
                    {{ row.kedalaman_bawah }}
                    {% endif %}
                    </td>
                    <td>
                    {% if row.kedalaman_atas == 'NULL' %}
                    {% trans "Terdampak" %}
                    {% else %}
                    {{ row.kedalaman_atas }}
                    {% endif %}
                    </td>
                    <td>{{ row.durasi_bawah }}</td>
                    <td>{{ row.durasi_atas }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p class="text-center">{% trans "Error: no config file found." %}</p>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block extra_footer %}
{% endblock %}